### PR TITLE
fix by defining new method

### PR DESCRIPTION
**Pull request by GantMan**
this should fix the image crash.   @twerth please corroborate that it does.

### CODE REVIEW

**Comment by GantMan** [comment]
it wasn't easy, but Mark and I got a screenshare going, lol!

**Comment by markrickert** [comment]
Code Copyright 2015, Mark Rickert. Typed by proxy through Gant.

**Comment by markrickert** [comment]
Why the heck is travis not catching these new pull requests?

**Comment by GantMan** [comment]
I'm going to have to take credit for gant_uiview_styler.rb naming conventions.   That's the real gold.

**Comment by squidpunch** [comment]
travis was never enabled on RP - and I dont think I have rights to do that

On Mon, Mar 2, 2015 at 4:27 PM, Mark Rickert <notifications@github.com>
wrote:

> Why the heck is travis not catching these new pull requests?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/infinitered/redpotion/pull/52#issuecomment-76828936>.
>



-- 
[image: MeYou Health][image: FB]
<http://www.facebook.com/profile.php?id=1303234885#!/meyouhealth>[image: T]
<http://twitter.com/#!/meyouhealth>[image: RSS]
<http://www.meyouhealth.com/blog/>[image: YT]
<http://www.youtube.com/user/meyouhealthvideos>[image: F]
<http://www.flickr.com/photos/meyouhealth>
*David Larrabee*Lead Rails Engineer
MeYou Health - the social well-being company27-43 Wormwood Street, 6th Floor
Boston, MA 02110
Phone: 763-260-4192www.meyouhealth.com
david.larrabee@meyouhealth.com
MeYou Health is a Healthways, Inc. company

**Comment by GantMan** [comment]
this is where we all blame Todd :hammer:

**Comment by squidpunch** [comment]
@markrickert I added the travis config, but i think the switch in travis isnt switched on (dont think travis has ever run on RP)

**Pull request merged**
