### PR TITLE
Add data table screen

### PR DESCRIPTION
**Pull request by squidpunch**
First pass at adding the functionality for #16 

This adds a new screen, which will use a custom cell, custom mode, and custom scope to populate the table.  Sample app updated to show functionality

### CODE REVIEW

**Comment by markrickert** [comment]
Just fyi, I'm seeing `will_appear` called twice when creating a screen and calling `open` on it. Perhaps related to the double attributes setting?

**Comment by squidpunch** [comment]
@markrickert I know there was a previous bug that sounded a bit like that.  (screen calling will_appear twice from what I recall).

The attributes thing seems like thats how they are doing it in ProMotion (from what I remember).  They set attributes when the cell is created, and then they set them again when its about to display - and I think its so that styling is done properly, etc...  But in my case of the sample app changes I made for this PR I had to work around that problem with removing the event and adding it again thats why I called it out.  I thought it was strange but didnt have a specific work around for it - and as @twerth mentioned this was getting a bit on the larger side to review too :smile: 

for reference I reported what you are seeing here: #24 and I believe it was supposed to be fixed, wonder if it came back, or if its a specific screen type that has the issue still?

**Comment by GantMan** [comment]
dude, that's some timing.  I JUST saw `will_appear` double calling.   @markrickert let me know what your fix is.

**Comment by markrickert** [comment]
Yeah, i think it's creating some of the slowness issues on our current project. It's creating things twice o_O

I'll have to look into this a bit more and see if i can fix.

**Comment by squidpunch** [comment]
interesting - sounds like it came back or another place its happening.  I can try and look at it again if I can reproduce as well, but you guys might beat me to it :+1:

**Comment by jamonholmgren** [comment]
Interested in knowing if PM is causing this.

**Comment by squidpunch** [comment]
Well I think it's more of the use case. 

Using onload to add views to a cell and PM calls onload  on cell creation and on cell will appear, at least that's how I remember it when I was building this out. Can't verify at the moment on the subway.

**Comment by jamonholmgren** [comment]
`will_appear` is only called from `view_will_appear(animated)`, which in turn is only called when `viewWillAppear(animated)` is triggered. Perhaps something else is going on? View getting inserted and removed and re-inserted?

**Comment by squidpunch** [comment]
@jamonholmgren sorry I mis-spoke (and perhaps mis-remembered).  What I was referring to is `set_attributes` being called twice (and what I mentioned when I created this PR.  I am not 100% sure thats what the issue @markrickert and @GantMan see - I think its a different bug actually, one that I previously reported in #12 @twerth fixed.

Just to clarify what I was saying about the double call using a PM Screen.

The reason we hare calling `set_attributes` twice in redpotion is because we call `cell.setup` in the creation of our cell,
https://github.com/infinitered/redpotion/blob/master/lib/project/pro_motion/table.rb#L13 which is really just a repeat of 
https://github.com/clearsightstudio/ProMotion/blob/e50dff3452b3229cbb652e746b892516525899ec/lib/ProMotion/table/table.rb#L133
with the addition of `new_cell.send(:on_load) if new_cell.respond_to?(:on_load)`

but then again its called in `def tableView(table_view, willDisplayCell: table_cell, forRowAtIndexPath: index_path)`
https://github.com/clearsightstudio/ProMotion/blob/e50dff3452b3229cbb652e746b892516525899ec/lib/ProMotion/table/table.rb#L201

Like I said I think we are talking about two different things though...


let me know if you guys got anywhere debugging this - I should have some time tonight to dedicate to troubleshooting it as well :+1:

**Pull request merged**
