### PR TITLE
Update to ProMotion 2.3+

### PR DESCRIPTION
**Pull request by jamonholmgren**
Removed unnecessary workarounds.

### CODE REVIEW

**Comment by squidpunch** [comment]
@jamonholmgren can you give this a rebase?

**Comment by markrickert** [comment]
Done. Waiting on travis.

**Comment by markrickert** [comment]
I updated the gemspec, but not the docs. Just fixed.

**Comment by GantMan** [comment]
:+1:

**Comment by jamonholmgren** [comment]
Thanks, guys!

**Pull request merged**
