### PR TITLE
relocate instruction in comments

### PR DESCRIPTION
**Pull request by chrislerum**

### CODE REVIEW

**Comment by twerth** [comment]
Cool, can you change the redpotion-template also?

**Comment by squidpunch** [comment]
:+1:

**Comment by chrislerum** [comment]
Thought I got'm all. Searched repo for "Remove the following" and only came up with two.

**Comment by squidpunch** [comment]
@chrislerum its another repo that drives that https://github.com/infinitered/redpotion-template

**Comment by squidpunch** [comment]
thanks @chrislerum

**Pull request merged**
