### PR TITLE
reapply_styles is available from screen directly

### PR DESCRIPTION
**Pull request by squidpunch**

### CODE REVIEW

**Comment by GantMan** [comment]
Very cool!

**Comment by GantMan** [comment]
Squid.  To me it looks like you should also take care of [existing instances](https://github.com/squidpunch/redpotion/blob/master/app/screens/home_screen.rb#L50) in the PR.

yes?

**Comment by squidpunch** [comment]
yup totally forgot about the existing screens!  will update this evening.

**Comment by squidpunch** [comment]
all set @GantMan

**Comment by GantMan** [comment]
you're on :fire:

**Pull request merged**
