### PR TITLE
automate bundle and pod installation

### PR DESCRIPTION
**Pull request by willrax**
This will automatically run both `bundle` and `rake pod:install` something that is required every time, but easily overlooked. It will also output this to the shell so the user can see the commands taking place.

```bash
👉 potion create example-app
Creating app
Template Cloning redpotion-template template
Template redpotion-template already exists, performing a pull
From github.com:infinitered/redpotion-template
 * branch            master     -> FETCH_HEAD
Running bundle...
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2

# etc etc etc
```

### CODE REVIEW

**Comment by squidpunch** [comment]
Nice!

**Comment by willrax** [comment]
@twerth yep. It woks just like the rails cli, runs the commands and leaves you where you ran the `potion` command. Im guessing that because we cd in and run the command in the same subshell it works fine.

It's a pretty common practice to run these setup commands both rails and ember-cli for example do the same thing. It's also something that you need to do in order to run the application and get going.

**Comment by twerth** [comment]
Hey Will, but you have the command `rake spec` and you won't be int he right folder.

**Comment by willrax** [comment]
Do you think that would trip developers up? Maybe adding back the `cd command` would help with that.

**Comment by twerth** [comment]
It's not big deal, of course, but noting.

**Comment by willrax** [comment]
Absolutely, I definitely don't want to add something that isn't a good fit or confuses first time users etc

**Pull request merged**
