### PR TITLE
Use splats properly

### PR DESCRIPTION
**Pull request by squidpunch**
* thanks @jamonholmgren

### CODE REVIEW

**Comment by jamonholmgren** [comment]
splat

**Comment by GantMan** [comment]
LOL @jamonholmgren 

Classic followup


splat

**Comment by squidpunch** [comment]
2 awesome gifs, means self merge! :)

**Comment by kevinvangelder** [comment]
Is there any reason we aren't also doing this here or was it just missed?

https://github.com/infinitered/redpotion/blob/master/lib/project/ext/object.rb#L11

**Comment by squidpunch** [comment]
@kevinvangelder overlooked - I wrote the other methods, and Todd wrote that one.  Totally planned on replacing that too...and forget :ghost:

thanks for the reminder.  I can push a commit fixing it later today, or if you want to PR it, feel free!

**Pull request merged**
