### PR TITLE
Fixes CLI hang & makes sure to exclude all CDQ when using --skip-cdq

### LINKED ISSUE #42: "potion create my_new_app --skip-cdq" should remove cdq.yml and schemas folder
While testing `potion create my_new_app --skip-cdq` I noticed these still exist:

* /resources/cdq.yml
* /schemas

### LINKED ISSUE #43: "potion create model foo" hangs
`potion create model foo` just sits there, waiting for something, the train perhaps.

### PR DESCRIPTION
**Pull request by squidpunch**
* fixes #43  introduced in 3c54fb1914a663eff8b2f7fd2fd6f6c9a357fc56
 * fixes #42

### CODE REVIEW

**Comment by GantMan** [comment]
@markrickert  and I hate that hang!   Good fix bud!

**Comment by squidpunch** [comment]
:+1: @GantMan

**Comment by twerth** [comment]
Thanks Squid

**Comment by squidpunch** [comment]
Anytime!

**Pull request merged**
