### PR TITLE
Adds CDQ and AFMotion removal tasks

### PR DESCRIPTION
**Pull request by squidpunch**

### CODE REVIEW

**Comment by twerth** [comment]
Neat. Is this ready to go David?

**Comment by squidpunch** [comment]
Worked for me when I gave it a test run. Should be 👍

**Comment by squidpunch** [comment]
the only thing I am not loving is the Afmotion removal.  It's just removing the gem, I think most people could do that and would do that rather than using a command line, I don't see harm in having it - just wonder how useful it is.

I will take a pass at the installer version soon (`potion create blah --without-cdq`) but I can make that a separate PR

**Comment by twerth** [comment]
Yeah, AFMotion is really just to be consistent with CDQ removal. Maybe later it will be more though as we add some AFNetworking defaults

**Pull request merged**
