### PR TITLE
Modify implementation of how data tables define cells

### LINKED ISSUE #67: Require the cell template included in the model - DataTableScreen
Per a discussion we had on #64, I would like to propose that we enforce that the model is where the cell structure is defined.  It's cleaner, and more intention leading.  

@markrickert and I both agree that we prefer forcing the dev specify the cell be in the model.  We should probably include that the cell method is implemented on the model and raise an error if not if we are going to be forcing that the cell is defined in the model used for the screen.

I am interested in others thoughts, agree? disagree?  Dont care?  Chime in now!

### PR DESCRIPTION
**Pull request by squidpunch**
* We want a clean, clear, but flexible interface for using data tables
  * We want the model to define our cell
  * We want to be informative to the user if they do not define the cell

should close #67, thanks @markrickert for helping formulate this idea!

### CODE REVIEW

**Comment by markrickert** [comment]
Nice job with the implementation! It also has the added benefit of making the code smaller and cleaner.

**Comment by jamonholmgren** [comment]
I love it!

**Comment by markrickert** [comment]
We should probably start documenting this somewhere.

**Comment by squidpunch** [comment]
Yeah we don't have the docs setup yet though right?. I can add doc commit if so.

**Comment by squidpunch** [comment]
@markrickert threw together something in the readme - which is just pulling out the example from the sample app.

**Comment by squidpunch** [comment]
anything else we should do here guys? Or is this good to be merged? :)

**Comment by jamonholmgren** [comment]
:shipit:

**Comment by squidpunch** [comment]
:bomb: :boom:

**Pull request merged**
