### PR TITLE
Reduce code duplication for better codeclimate score.

### PR DESCRIPTION
**Pull request by markrickert**
This was the only duplication found by codeclimate and it also makes a good example of how you can define methods in the `ApplicationStylesheet` and use it in multiple stylesheets.

### CODE REVIEW

**Comment by twerth** [comment]
Sorry man, I'm not merging this. This is a bad example of how to do this.

**Comment by markrickert** [comment]
Raises CC score from 3.83 -> 4.0

**Comment by jamonholmgren** [comment]
denied

**Comment by jamonholmgren** [comment]
Maybe just mix up the example with different code instead?

**Comment by markrickert** [comment]
Damn, that's cold, @jamonholmgren :cry:

**Comment by twerth** [comment]
Heh, that is cold.

**Comment by jamonholmgren** [comment]
Shoot the messenger!

**Comment by squidpunch** [comment]
:laughing:

**Pull request closed without merging**
